services:
  mysql-svc:
    image: mysql:8.0.28
    container_name: test-mysql
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: forgottendb
      MYSQL_USER: forgottenuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/sql/:/docker-entrypoint-initdb.d/

  phpmyadmin-svc:
    image: phpmyadmin/phpmyadmin
    container_name: test-phpmyadmin
    depends_on:
      mysql-svc:
        condition: service_started
    environment:
      PMA_HOST: mysql-svc
      PMA_PORT: 3306
      MYSQL_USER: forgottenuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 9090:80